# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoTracker' do
	pod 'CryptoCurrencyKit'
	pod 'SwiftyJSON'
  	pod 'Alamofire', '~> 4.6'
  	pod 'SDWebImage'
end
